name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configurar cache do Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Instalar dependências
        run: cargo build --release

      - name: Criar arquivo .env
        run: |
          echo "DRIVER=postgresql" >> .env
          echo "USER=postgres" >> .env
          echo "PASSWORD=postgres" >> .env
          echo "HOST=localhost" >> .env
          echo "PORT=5432" >> .env
          echo "DATABASE=postgres" >> .env
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres" >> .env

      - name: Rodar migrações (se houver)
        run: cargo install sqlx-cli && sqlx database setup
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres

      - name: Rodar testes
        run: cargo test

      - name: Rodar aplicação
        run: cargo run
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
