name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.81.0 # Ou 'stable' para a versão mais recente
          components: clippy, rustfmt # Instala clippy e rustfmt (opcional)

      - name: Clean Cargo Cache
        run: cargo clean

      - name: Build
        run: cargo build --release

      - name: Run Tests
        run: cargo test

      - name: Run Clippy
        run: cargo clippy -- -D warnings # Executa clippy para verificar warnings (opcional)

      - name: Run Rustfmt
        run: cargo fmt -- --check # Executa rustfmt para verificar formatação (opcional)