name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/dashrs_test" # Altere conforme necessário

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dashrs_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Create .env file
      run: |
        echo "DATABASE_URL=$DATABASE_URL" > .env
        echo "RUST_LOG=info" >> .env

    - name: Build com debug
      run: cargo build --verbose 2>&1 | tee build.log

    - name: Exibir logs do build no GitHub Actions
      run: cat build.log

    - name: Run tests
      run: cargo test --verbose

    - name: Run the project
      run: cargo run
